spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ceb_backend
    username: postgres
    password: MyNewPass
    driver-classname: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql:true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
      cache: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
        forget_password_url: http://localhost:4200/reset-password

  pricing:
    base-rate: 10
    tax-rate: 5

  file:
    uploads:
      base-path: ./uploads
      temp-file-path: ./temp
      user-path: ./users
  env:
    urls:
      app-url: http://localhost:8080



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


logging:
  level:
    org:
      hibernate: info
      hibernate.SQL: debug
      hibernate.orm.jdbc.bind: trace
      hibernate.stat: debug
      hibernate.SQL_SLOW: info
      hibernate.cache: debug